### ISSUE TITLE
Background Colour Change

### ISSUE THREAD

**Issue by captainsalvos** [anthonyeden/ProPresenter-Stage-Display-Python#10]
Hi Anthony, 

Can we have the option to change the background colour for chromakey?

**Comment by anthonyeden** [comment]
Hey @captainsalvos ,
I've implemented this in commit c796977.

You can specify config options "BackgroundColour" and "TextColour", which accept any standard six-digit hex string (e.g. #FFFFFF for white, #000000 for black, #00FF00 for green).
