### ISSUE TITLE
Errors on Fresh Install

### ISSUE THREAD

**Issue by theblanchard** [anthonyeden/ProPresenter-Stage-Display-Python#11]
I'm having trouble installing and setting this up. I have a fresh install of Raspbian, and have only installed this single python app.

I am unable to find python2 using apt-get, I have installed 2.7 & 3, with no success. 

Running `python2 StageDisplay.py` or `python2.7 StageDisplay.py` yields the following: 
<img width="573" alt="screenshot 2018-12-28 13 49 37" src="https://user-images.githubusercontent.com/13232/50529306-ceb0fd80-0aa8-11e9-9d4d-2dae9737dbcb.png">

Running `python3 StageDisplay.py` yields this:
<img width="567" alt="screenshot 2018-12-28 14 01 03" src="https://user-images.githubusercontent.com/13232/50529338-05871380-0aa9-11e9-9b0f-0a3e99e76ca1.png">

Please advise, I'd really love to get this up and running, but my python knowledge is limited.

**Comment by leorac** [comment]
Hi,
I think it's not a Python problem. The python version is right, but basing on what I see (but tell me if I'm wrong) you are trying to run the application under console, without a X interface. You should install or enable the Desktop Environment (LXDE is the default) than run the script from that.

**Comment by theblanchard** [comment]
Running directly from the Pi fixed the issue. Thanks!
