### ISSUE TITLE
Request: OBS Native Version

### ISSUE THREAD

**Issue by egoosey** [anthonyeden/ProPresenter-Stage-Display-Python#7]
Hello,

Since OBS now support native scripting for python, is there a way to add support for that? I tried just loading the Stage Display.py into OBS but nothing happens. 

Here are some resources:
https://github.com/obsproject/obs-studio/releases/tag/21.0.1

https://obsproject.com/forum/resources/categories/scripts.5/

**Comment by egoosey** [comment]
Here is the dev resource. 

https://obsproject.com/docs/scripting.html

**Comment by egoosey** [comment]
![image](https://user-images.githubusercontent.com/5839303/37834032-4796e3e8-2e83-11e8-8c93-859690b60550.png)

![image](https://user-images.githubusercontent.com/5839303/37834068-51f6927a-2e83-11e8-9870-7c63b13d9714.png)

**Comment by egoosey** [comment]
@anthonyeden I'm not sure if I have to tag you or not so I did anyway. :)

**Comment by anthonyeden** [comment]
Hi @egoosey,

Thanks for that. Someone else requested the same thing a few weeks back, and from what I can tell there's no way to generate video output with their Python scripting - just control features within OBS.

My suggestion (which you may already be doing) is to use the 'Window Capture' source in OBS.

Feel free to let me know if you (or anyone else) works out a way to do this.

**Comment by egoosey** [comment]
@anthonyeden I have been able to implement this into OBS as a browser source using the below from @sdboer78. Works pretty well. I changed the page background to green then just keyed it out. I think this will work well for folks wanting it native in OBS. I still use your version for other seperate displays such as for our deaf ministry. 

https://github.com/sdboer78/propresenter-stagedisplay

**Comment by leorac** [comment]
> Hi @egoosey,
> 
> Thanks for that. Someone else requested the same thing a few weeks back, and from what I can tell there's no way to generate video output with their Python scripting - just control features within OBS.
> 
> My suggestion (which you may already be doing) is to use the 'Window Capture' source in OBS.
> 
> Feel free to let me know if you (or anyone else) works out a way to do this.

I'm trying to do this but on Windows the application only works in Full Screen Mode. It closes when I press Esc key. Is that a way to run the application in Window mode, so that i can capture it with OBS?

**Comment by egoosey** [comment]
Hi @nardyn,

I was able to accomplish this by running this
https://github.com/sdboer78/propresenter-stagedisplay as a browser source
in OBS. Let me know if you have any questions.

Thanks,
Eric

**Comment by leorac** [comment]
It supports lower third?

Il giorno mer 26 dic 2018, 14:47 Eric Goosey <notifications@github.com> ha
scritto:

> Hi @nardyn,
>
> I was able to accomplish this by running this
> https://github.com/sdboer78/propresenter-stagedisplay as a browser source
> in OBS. Let me know if you have any questions.
>
> Thanks,
> Eric
>

**Comment by egoosey** [comment]
Yes.

**Comment by leorac** [comment]
It perfectly works!! Thank you very much!

**Comment by armosandor** [comment]
Hi,

I'm facing an issue with this as for some reason after like half a second of selecting a source in Propresenter the clock is getting displayed. No matter how I configure the stage display the changes won't affect the image I get when viewing the index.html file. I guess that's normal behaviour, but I cannot figure out what's causing the displayed text to jump to the clock.

Any help would be much appreciated.

Kind Regards,
Andor

**Comment by egoosey** [comment]
Andor,

Do you mean that you only see a clock at the top? If do this is normal. The words should be displayed underneath with the "next slide" after that. Could you provide a screen capture?

**Comment by armosandor** [comment]
Thanks for your prompt reply.
Please see below the video on the link that will show you what happens.

https://photos.app.goo.gl/VdfjNK8nRSEVXFeZ6

**Comment by egoosey** [comment]
Is this the default configuration? Have you altered the config file in anyway?

**Comment by armosandor** [comment]
It is the default configuration in the config.js file.
I obviously defined the IP in there and the App password.
I didn't change anything in the css nor in the index files.

**Comment by egoosey** [comment]
@armosandor Could you please open a new issue for this? I think this isn't related to the original thread.
