### ISSUE TITLE
Disable screensaver

### ISSUE THREAD

**Issue by kebab1** [anthonyeden/ProPresenter-Stage-Display-Python#8]
Instruction to disable blank screen after 10 minutes on raspbian would be helpful.

sudo nano /etc/lightdm/lightdm.conf
find (ctrl + w) #xserver-command=X
Change it to xserver-command=X -s 0 dpms
save and exit (reboot)

**Comment by anthonyeden** [comment]
Hi @kebab1,
Thanks for this. I've added these instructions, plus a couple of other methods, to the README file.
